flag_map = {
    'Argentina': 'ar', 'Australia': 'au', 'Belgium': 'be', 'Brazil': 'br',
    'Cameroon': 'cm', 'Canada': 'ca', 'Costa Rica': 'cr', 'Croatia': 'hr',
    'Denmark': 'dk', 'Ecuador': 'ec', 'England': 'gb-eng', 'France': 'fr',
    'Germany': 'de', 'Ghana': 'gh', 'Iran': 'ir', 'Japan': 'jp',
    'Mexico': 'mx', 'Morocco': 'ma', 'Netherlands': 'nl', 'Poland': 'pl',
    'Portugal': 'pt', 'Qatar': 'qa', 'Saudi Arabia': 'sa', 'Senegal': 'sn',
    'Serbia': 'rs', 'South Korea': 'kr', 'Spain': 'es', 'Switzerland': 'ch',
    'Tunisia': 'tn', 'Uruguay': 'uy', 'USA': 'us', 'Wales': 'gb-wls',
    'Korea Republic': 'kr', 'South Africa': 'za', 'Scotland': 'gb-sct',
    'Haiti': 'ht', 'Paraguay': 'py', 'Curacao': 'cw', 'Curaçao': 'cw',
    'Ivory Coast': 'ci', 'Côte d\'Ivoire': 'ci', 'Cote d\'Ivoire': 'ci',
    'Colombia': 'co', 'Chile': 'cl', 'Peru': 'pe', 'Venezuela': 've',
    'Bolivia': 'bo', 'Panama': 'pa', 'Honduras': 'hn', 'Jamaica': 'jm',
    'Trinidad and Tobago': 'tt', 'El Salvador': 'sv', 'Guatemala': 'gt',
    'Algeria': 'dz', 'Nigeria': 'ng', 'Egypt': 'eg', 'Burkina Faso': 'bf',
    'New Zealand': 'nz', 'Cabo Verde': 'cv', 'Norway': 'no', 'Austria': 'at',
    'Jordan': 'jo', 'Uzbekistan': 'uz',
    'Democratic Republic of the Congo': 'cd',
    'DR Congo': 'cd',
    'Turkey': 'tr', 'Iraq': 'iq', 'Bosnia and Herzegovina': 'ba',
    'Sweden': 'se', 'Czech Republic': 'cz',
}

abbr_map = {
    'Argentina': 'ARG', 'Australia': 'AUS', 'Belgium': 'BEL', 'Brazil': 'BRA',
    'Cameroon': 'CMR', 'Canada': 'CAN', 'Costa Rica': 'CRC', 'Croatia': 'CRO',
    'Denmark': 'DEN', 'Ecuador': 'ECU', 'England': 'ENG', 'France': 'FRA',
    'Germany': 'GER', 'Ghana': 'GHA', 'Iran': 'IRN', 'Japan': 'JPN',
    'Mexico': 'MEX', 'Morocco': 'MAR', 'Netherlands': 'NED', 'Poland': 'POL',
    'Portugal': 'POR', 'Qatar': 'QAT', 'Saudi Arabia': 'KSA', 'Senegal': 'SEN',
    'Serbia': 'SRB', 'South Korea': 'KOR', 'Spain': 'ESP', 'Switzerland': 'SUI',
    'Tunisia': 'TUN', 'Uruguay': 'URU', 'USA': 'USA', 'Wales': 'WAL',
    'Korea Republic': 'KOR', 'South Africa': 'RSA', 'Scotland': 'SCO',
    'Haiti': 'HAI', 'Paraguay': 'PAR', 'Curacao': 'CUW', 'Curaçao': 'CUW',
    "Ivory Coast": 'CIV', "Côte d'Ivoire": 'CIV', "Cote d'Ivoire": 'CIV',
    'Colombia': 'COL', 'Chile': 'CHI', 'Peru': 'PER', 'Venezuela': 'VEN',
    'Bolivia': 'BOL', 'Panama': 'PAN', 'Honduras': 'HON', 'Jamaica': 'JAM',
    'Trinidad and Tobago': 'TRI', 'El Salvador': 'SLV', 'Guatemala': 'GUA',
    'Algeria': 'ALG', 'Nigeria': 'NGA', 'Egypt': 'EGY', 'Burkina Faso': 'BFA',
    'New Zealand': 'NZL', 'Cabo Verde': 'CPV', 'Norway': 'NOR', 'Austria': 'AUT',
    'Jordan': 'JOR', 'Uzbekistan': 'UZB', 'DR Congo': 'COD',
    'Turkey': 'TUR', 'Iraq': 'IRQ', 'Bosnia and Herzegovina': 'BIH',
    'Sweden': 'SWE', 'Czech Republic': 'CZE',
}

translations = {
    'Argentina': 'Argentina',
    'Australia': 'Austrália',
    'Belgium': 'Bélgica',
    'Brazil': 'Brasil',
    'Cameroon': 'Camarões',
    'Canada': 'Canadá',
    'Costa Rica': 'Costa Rica',
    'Croatia': 'Croácia',
    'Denmark': 'Dinamarca',
    'Ecuador': 'Equador',
    'England': 'Inglaterra',
    'France': 'França',
    'Germany': 'Alemanha',
    'Ghana': 'Gana',
    'Iran': 'Irã',
    'Japan': 'Japão',
    'Mexico': 'México',
    'Morocco': 'Marrocos',
    'Netherlands': 'Holanda',
    'Poland': 'Polônia',
    'Portugal': 'Portugal',
    'Qatar': 'Catar',
    'Saudi Arabia': 'Arábia Saudita',
    'Senegal': 'Senegal',
    'Serbia': 'Sérvia',
    'South Korea': 'Coreia do Sul',
    'Spain': 'Espanha',
    'Switzerland': 'Suíça',
    'Tunisia': 'Tunísia',
    'Uruguay': 'Uruguai',
    'USA': 'Estados Unidos',
    'Wales': 'País de Gales',
    'Korea Republic': 'Coreia do Sul',
    'South Africa': 'África do Sul',
    'Scotland': 'Escócia',
    'Haiti': 'Haiti',
    'Paraguay': 'Paraguai',
    'Curacao': 'Curaçao',
    'Curaçao': 'Curaçao',
    "Ivory Coast": 'Costa do Marfim',
    "Côte d'Ivoire": 'Costa do Marfim',
    "Cote d'Ivoire": 'Costa do Marfim',
    'Colombia': 'Colômbia',
    'Chile': 'Chile',
    'Peru': 'Peru',
    'Venezuela': 'Venezuela',
    'Bolivia': 'Bolívia',
    'Panama': 'Panamá',
    'Honduras': 'Honduras',
    'Jamaica': 'Jamaica',
    'Trinidad and Tobago': 'Trinidad e Tobago',
    'El Salvador': 'El Salvador',
    'Guatemala': 'Guatemala',
    'Algeria': 'Argélia',
    'Nigeria': 'Nigéria',
    'Egypt': 'Egito',
    'Burkina Faso': 'Burkina Faso',
    'New Zealand': 'Nova Zelândia',
    'Cabo Verde': 'Cabo Verde',
    'Norway': 'Noruega',
    'Austria': 'Áustria',
    'Jordan': 'Jordânia',
    'Uzbekistan': 'Uzbequistão',
    'Democratic Republic of the Congo': 'RD Congo',
    'DR Congo': 'RD Congo',
    'Turkey': 'Turquia',
    'Iraq': 'Iraque',
    'Bosnia and Herzegovina': 'Bósnia',
    'Sweden': 'Suécia',
    'Czech Republic': 'República Checa',
}

translations_reduced = {
    'Argentina': 'Argentina',
    'Australia': 'Austrália',
    'Belgium': 'Bélgica',
    'Brazil': 'Brasil',
    'Cameroon': 'Camarões',
    'Canada': 'Canadá',
    'Costa Rica': 'Costa Rica',
    'Croatia': 'Croácia',
    'Denmark': 'Dinamarca',
    'Ecuador': 'Equador',
    'England': 'Inglaterra',
    'France': 'França',
    'Germany': 'Alemanha',
    'Ghana': 'Gana',
    'Iran': 'Irã',
    'Japan': 'Japão',
    'Mexico': 'México',
    'Morocco': 'Marrocos',
    'Netherlands': 'Holanda',
    'Poland': 'Polônia',
    'Portugal': 'Portugal',
    'Qatar': 'Catar',
    'Saudi Arabia': 'Arábia S',
    'Senegal': 'Senegal',
    'Serbia': 'Sérvia',
    'South Korea': 'Coréia',
    'Spain': 'Espanha',
    'Switzerland': 'Suíça',
    'Tunisia': 'Tunísia',
    'Uruguay': 'Uruguai',
    'USA': 'EUA',
    'Wales': 'País de Gales',
    'Korea Republic': 'Coréia',
    'South Africa': 'África S',
    'Scotland': 'Escócia',
    'Haiti': 'Haiti',
    'Paraguay': 'Paraguai',
    'Curacao': 'Curaçao',
    'Curaçao': 'Curaçao',
    "Ivory Coast": 'Costa M',
    "Côte d'Ivoire": 'Costa M',
    "Cote d'Ivoire": 'Costa M',
    'Colombia': 'Colômbia',
    'Chile': 'Chile',
    'Peru': 'Peru',
    'Venezuela': 'Venezuela',
    'Bolivia': 'Bolívia',
    'Panama': 'Panamá',
    'Honduras': 'Honduras',
    'Jamaica': 'Jamaica',
    'Trinidad and Tobago': 'Trinidad e Tobago',
    'El Salvador': 'El Salvador',
    'Guatemala': 'Guatemala',
    'Algeria': 'Argélia',
    'Nigeria': 'Nigéria',
    'Egypt': 'Egito',
    'Burkina Faso': 'Burkina Faso',
    'New Zealand': 'Nova Z',
    'Cabo Verde': 'Cabo V',
    'Norway': 'Noruega',
    'Austria': 'Áustria',
    'Jordan': 'Jordânia',
    'Uzbekistan': 'Uzbequi',
    'Democratic Republic of the Congo': 'Congo',
    'DR Congo': 'Congo',
    'Turkey': 'Turquia',
    'Iraq': 'Iraque',
    'Bosnia and Herzegovina': 'Bósnia',
    'Sweden': 'Suécia',
    'Czech Republic': 'R Checa',
}


PLAYER_ALIASES = {
    # Mbappé
    "kylian mbappe": "Mbappé",
    "kylian mbappé": "Mbappé",
    "mbappe": "Mbappé",
    "mbappé": "Mbappé",
    "Mbape": "Mbappé",
    "mbape": "Mbappé",

    # Vinicius
    "vinicius junior": "Vini Jr.",
    "vinícius junior": "Vini Jr.",
    "vinicius jr": "Vini Jr.",
    "vinícius jr": "Vini Jr.",
    "vini jr": "Vini Jr.",
    "vini jr.": "Vini Jr.",

    # Igor Thiago
    "igor thiago pirulito": "Igor Thiago",
    "igor thiago": "Igor Thiago",

    # Lamine Yamal
    "lamina yamal": "Lamine Yamal",
    "yamal": "Lamine Yamal",

    # Harry Kane
    "kane": "Harry Kane",
    "harry kane": "Harry Kane",

    # Neymar
    "baleno": "Neymar"

}

CAMPEAO = ""

ARTILHEIRO = ""

MELHOR_JOGADOR = ""

ZEBRA = ""

FAVORITO = ""

ANFITRIAO = ""

# FIFA World Rankings (as of December 2024/January 2025)
# Lower number = better ranking (1 is best)
# Used as final tiebreaker for group standings
fifa_ranking = {
    'Argentina': 1,
    'France': 2,
    'Spain': 3,
    'England': 4,
    'Brazil': 5,
    'Belgium': 6,
    'Netherlands': 7,
    'Portugal': 8,
    'Colombia': 9,
    'Italy': 10,
    'Uruguay': 11,
    'Croatia': 12,
    'Germany': 13,
    'Morocco': 14,
    'Switzerland': 15,
    'USA': 16,
    'Mexico': 17,
    'Japan': 18,
    'Senegal': 19,
    'Iran': 20,
    'Denmark': 21,
    'South Korea': 22,
    'Korea Republic': 22,
    'Australia': 23,
    'Egypt': 24,
    'Ukraine': 25,
    'Turkey': 26,
    'Canada': 27,
    'Austria': 28,
    'Sweden': 29,
    'Poland': 30,
    'Nigeria': 31,
    'Ecuador': 32,
    'Tunisia': 33,
    'Algeria': 34,
    'Chile': 35,
    'Peru': 36,
    'Serbia': 37,
    'Czech Republic': 38,
    'Norway': 39,
    'Scotland': 40,
    'Costa Rica': 41,
    'Mali': 42,
    'Burkina Faso': 43,
    'Cameroon': 44,
    'Ivory Coast': 45,
    "Côte d'Ivoire": 45,
    "Cote d'Ivoire": 45,
    'South Africa': 46,
    'Venezuela': 47,
    'Ghana': 48,
    'Bosnia and Herzegovina': 49,
    'Paraguay': 50,
    'Panama': 51,
    'Jamaica': 52,
    'Qatar': 53,
    'Iraq': 54,
    'Cabo Verde': 55,
    'DR Congo': 56,
    'Democratic Republic of the Congo': 56,
    'Honduras': 57,
    'Uzbekistan': 58,
    'Jordan': 59,
    'New Zealand': 60,
    'Bolivia': 61,
    'El Salvador': 62,
    'Haiti': 63,
    'Curacao': 64,
    'Curaçao': 64,
    'Guatemala': 65,
    'Trinidad and Tobago': 66,
    'Saudi Arabia': 67,
    'Wales': 68,
}