flag_map = {
    'Argentina': 'ar', 'Australia': 'au', 'Belgium': 'be', 'Brazil': 'br',
    'Cameroon': 'cm', 'Canada': 'ca', 'Costa Rica': 'cr', 'Croatia': 'hr',
    'Denmark': 'dk', 'Ecuador': 'ec', 'England': 'gb-eng', 'France': 'fr',
    'Germany': 'de', 'Ghana': 'gh', 'Iran': 'ir', 'Japan': 'jp',
    'Mexico': 'mx', 'Morocco': 'ma', 'Netherlands': 'nl', 'Poland': 'pl',
    'Portugal': 'pt', 'Qatar': 'qa', 'Saudi Arabia': 'sa', 'Senegal': 'sn',
    'Serbia': 'rs', 'South Korea': 'kr', 'Spain': 'es', 'Switzerland': 'ch',
    'Tunisia': 'tn', 'Uruguay': 'uy', 'USA': 'us', 'Wales': 'gb-wls',
    'Korea Republic': 'kr', 'South Africa': 'za', 'Scotland': 'gb-sct',
    'Haiti': 'ht', 'Paraguay': 'py', 'Curacao': 'cw', 'Curaçao': 'cw',
    'Ivory Coast': 'ci', 'Côte d\'Ivoire': 'ci', 'Cote d\'Ivoire': 'ci',
    'Colombia': 'co', 'Chile': 'cl', 'Peru': 'pe', 'Venezuela': 've',
    'Bolivia': 'bo', 'Panama': 'pa', 'Honduras': 'hn', 'Jamaica': 'jm',
    'Trinidad and Tobago': 'tt', 'El Salvador': 'sv', 'Guatemala': 'gt',
    'Algeria': 'dz', 'Nigeria': 'ng', 'Egypt': 'eg', 'Burkina Faso': 'bf',
    'New Zealand': 'nz', 'Cabo Verde': 'cv', 'Norway': 'no', 'Austria': 'at',
    'Jordan': 'jo', 'Uzbekistan': 'uz',
    'Democratic Republic of the Congo': 'cd', 'Turkey': 'tr', 'Iraq': 'iq', 'Bosnia and Herzegovina': 'ba',
    'Sweden': 'se', 'Czech Republic': 'cz',
}

abbr_map = {
    'Argentina': 'ARG', 'Australia': 'AUS', 'Belgium': 'BEL', 'Brazil': 'BRA',
    'Cameroon': 'CMR', 'Canada': 'CAN', 'Costa Rica': 'CRC', 'Croatia': 'CRO',
    'Denmark': 'DEN', 'Ecuador': 'ECU', 'England': 'ENG', 'France': 'FRA',
    'Germany': 'GER', 'Ghana': 'GHA', 'Iran': 'IRN', 'Japan': 'JPN',
    'Mexico': 'MEX', 'Morocco': 'MAR', 'Netherlands': 'NED', 'Poland': 'POL',
    'Portugal': 'POR', 'Qatar': 'QAT', 'Saudi Arabia': 'KSA', 'Senegal': 'SEN',
    'Serbia': 'SRB', 'South Korea': 'KOR', 'Spain': 'ESP', 'Switzerland': 'SUI',
    'Tunisia': 'TUN', 'Uruguay': 'URU', 'USA': 'USA', 'Wales': 'WAL',
    'Korea Republic': 'KOR', 'South Africa': 'RSA', 'Scotland': 'SCO',
    'Haiti': 'HAI', 'Paraguay': 'PAR', 'Curacao': 'CUW', 'Curaçao': 'CUW',
    "Ivory Coast": 'CIV', "Côte d'Ivoire": 'CIV', "Cote d'Ivoire": 'CIV',
    'Colombia': 'COL', 'Chile': 'CHI', 'Peru': 'PER', 'Venezuela': 'VEN',
    'Bolivia': 'BOL', 'Panama': 'PAN', 'Honduras': 'HON', 'Jamaica': 'JAM',
    'Trinidad and Tobago': 'TRI', 'El Salvador': 'SLV', 'Guatemala': 'GUA',
    'Algeria': 'ALG', 'Nigeria': 'NGA', 'Egypt': 'EGY', 'Burkina Faso': 'BFA',
    'New Zealand': 'NZL', 'Cabo Verde': 'CPV', 'Norway': 'NOR', 'Austria': 'AUT',
    'Jordan': 'JOR', 'Uzbekistan': 'UZB', 'Democratic Republic of the Congo': 'COD',
    'Turkey': 'TUR', 'Iraq': 'IRQ', 'Bosnia and Herzegovina': 'BIH',
    'Sweden': 'SWE', 'Czech Republic': 'CZE',
}

translations = {
    'Argentina': 'Argentina',
    'Australia': 'Austrália',
    'Belgium': 'Bélgica',
    'Brazil': 'Brasil',
    'Cameroon': 'Camarões',
    'Canada': 'Canadá',
    'Costa Rica': 'Costa Rica',
    'Croatia': 'Croácia',
    'Denmark': 'Dinamarca',
    'Ecuador': 'Equador',
    'England': 'Inglaterra',
    'France': 'França',
    'Germany': 'Alemanha',
    'Ghana': 'Gana',
    'Iran': 'Irã',
    'Japan': 'Japão',
    'Mexico': 'México',
    'Morocco': 'Marrocos',
    'Netherlands': 'Holanda',
    'Poland': 'Polônia',
    'Portugal': 'Portugal',
    'Qatar': 'Catar',
    'Saudi Arabia': 'Arábia Saudita',
    'Senegal': 'Senegal',
    'Serbia': 'Sérvia',
    'South Korea': 'Coreia do Sul',
    'Spain': 'Espanha',
    'Switzerland': 'Suíça',
    'Tunisia': 'Tunísia',
    'Uruguay': 'Uruguai',
    'USA': 'Estados Unidos',
    'Wales': 'País de Gales',
    'Korea Republic': 'Coreia do Sul',
    'South Africa': 'África do Sul',
    'Scotland': 'Escócia',
    'Haiti': 'Haiti',
    'Paraguay': 'Paraguai',
    'Curacao': 'Curaçao',
    'Curaçao': 'Curaçao',
    "Ivory Coast": 'Costa do Marfim',
    "Côte d'Ivoire": 'Costa do Marfim',
    "Cote d'Ivoire": 'Costa do Marfim',
    'Colombia': 'Colômbia',
    'Chile': 'Chile',
    'Peru': 'Peru',
    'Venezuela': 'Venezuela',
    'Bolivia': 'Bolívia',
    'Panama': 'Panamá',
    'Honduras': 'Honduras',
    'Jamaica': 'Jamaica',
    'Trinidad and Tobago': 'Trinidad e Tobago',
    'El Salvador': 'El Salvador',
    'Guatemala': 'Guatemala',
    'Algeria': 'Argélia',
    'Nigeria': 'Nigéria',
    'Egypt': 'Egito',
    'Burkina Faso': 'Burkina Faso',
    'New Zealand': 'Nova Zelândia',
    'Cabo Verde': 'Cabo Verde',
    'Norway': 'Noruega',
    'Austria': 'Áustria',
    'Jordan': 'Jordânia',
    'Uzbekistan': 'Uzbequistão',
    'Democratic Republic of the Congo': 'RD Congo',
    'Turkey': 'Turquia',
    'Iraq': 'Iraque',
    'Bosnia and Herzegovina': 'Bósnia',
    'Sweden': 'Suécia',
    'Czech Republic': 'República Checa',
}
