flag_map = {
    'Argentina': 'ar', 'Australia': 'au', 'Belgium': 'be', 'Brazil': 'br',
    'Cameroon': 'cm', 'Canada': 'ca', 'Costa Rica': 'cr', 'Croatia': 'hr',
    'Denmark': 'dk', 'Ecuador': 'ec', 'England': 'gb-eng', 'France': 'fr',
    'Germany': 'de', 'Ghana': 'gh', 'Iran': 'ir', 'Japan': 'jp',
    'Mexico': 'mx', 'Morocco': 'ma', 'Netherlands': 'nl', 'Poland': 'pl',
    'Portugal': 'pt', 'Qatar': 'qa', 'Saudi Arabia': 'sa', 'Senegal': 'sn',
    'Serbia': 'rs', 'South Korea': 'kr', 'Spain': 'es', 'Switzerland': 'ch',
    'Tunisia': 'tn', 'Uruguay': 'uy', 'USA': 'us', 'Wales': 'gb-wls',
    'Korea Republic': 'kr', 'South Africa': 'za', 'Scotland': 'gb-sct',
    'Haiti': 'ht', 'Paraguay': 'py', 'Curacao': 'cw', 'Curaçao': 'cw',
    'Ivory Coast': 'ci', 'Côte d\'Ivoire': 'ci', 'Cote d\'Ivoire': 'ci',
    'Colombia': 'co', 'Chile': 'cl', 'Peru': 'pe', 'Venezuela': 've',
    'Bolivia': 'bo', 'Panama': 'pa', 'Honduras': 'hn', 'Jamaica': 'jm',
    'Trinidad and Tobago': 'tt', 'El Salvador': 'sv', 'Guatemala': 'gt',
    'Algeria': 'dz', 'Nigeria': 'ng', 'Egypt': 'eg', 'Burkina Faso': 'bf',
    'New Zealand': 'nz', 'Cabo Verde': 'cv', 'Norway': 'no', 'Austria': 'at',
    'Jordan': 'jo', 'Uzbekistan': 'uz',
    'Democratic Republic of the Congo': 'cd',
    'DR Congo': 'cd',
    'Turkey': 'tr', 'Iraq': 'iq', 'Bosnia and Herzegovina': 'ba',
    'Sweden': 'se', 'Czech Republic': 'cz',
}

abbr_map = {
    'Argentina': 'ARG', 'Australia': 'AUS', 'Belgium': 'BEL', 'Brazil': 'BRA',
    'Cameroon': 'CMR', 'Canada': 'CAN', 'Costa Rica': 'CRC', 'Croatia': 'CRO',
    'Denmark': 'DEN', 'Ecuador': 'ECU', 'England': 'ENG', 'France': 'FRA',
    'Germany': 'GER', 'Ghana': 'GHA', 'Iran': 'IRN', 'Japan': 'JPN',
    'Mexico': 'MEX', 'Morocco': 'MAR', 'Netherlands': 'NED', 'Poland': 'POL',
    'Portugal': 'POR', 'Qatar': 'QAT', 'Saudi Arabia': 'KSA', 'Senegal': 'SEN',
    'Serbia': 'SRB', 'South Korea': 'KOR', 'Spain': 'ESP', 'Switzerland': 'SUI',
    'Tunisia': 'TUN', 'Uruguay': 'URU', 'USA': 'USA', 'Wales': 'WAL',
    'Korea Republic': 'KOR', 'South Africa': 'RSA', 'Scotland': 'SCO',
    'Haiti': 'HAI', 'Paraguay': 'PAR', 'Curacao': 'CUW', 'Curaçao': 'CUW',
    "Ivory Coast": 'CIV', "Côte d'Ivoire": 'CIV', "Cote d'Ivoire": 'CIV',
    'Colombia': 'COL', 'Chile': 'CHI', 'Peru': 'PER', 'Venezuela': 'VEN',
    'Bolivia': 'BOL', 'Panama': 'PAN', 'Honduras': 'HON', 'Jamaica': 'JAM',
    'Trinidad and Tobago': 'TRI', 'El Salvador': 'SLV', 'Guatemala': 'GUA',
    'Algeria': 'ALG', 'Nigeria': 'NGA', 'Egypt': 'EGY', 'Burkina Faso': 'BFA',
    'New Zealand': 'NZL', 'Cabo Verde': 'CPV', 'Norway': 'NOR', 'Austria': 'AUT',
    'Jordan': 'JOR', 'Uzbekistan': 'UZB', 'DR Congo': 'COD',
    'Turkey': 'TUR', 'Iraq': 'IRQ', 'Bosnia and Herzegovina': 'BIH',
    'Sweden': 'SWE', 'Czech Republic': 'CZE',
}

translations = {
    'Argentina': 'Argentina',
    'Australia': 'Austrália',
    'Belgium': 'Bélgica',
    'Brazil': 'Brasil',
    'Cameroon': 'Camarões',
    'Canada': 'Canadá',
    'Costa Rica': 'Costa Rica',
    'Croatia': 'Croácia',
    'Denmark': 'Dinamarca',
    'Ecuador': 'Equador',
    'England': 'Inglaterra',
    'France': 'França',
    'Germany': 'Alemanha',
    'Ghana': 'Gana',
    'Iran': 'Irã',
    'Japan': 'Japão',
    'Mexico': 'México',
    'Morocco': 'Marrocos',
    'Netherlands': 'Holanda',
    'Poland': 'Polônia',
    'Portugal': 'Portugal',
    'Qatar': 'Catar',
    'Saudi Arabia': 'Arábia Saudita',
    'Senegal': 'Senegal',
    'Serbia': 'Sérvia',
    'South Korea': 'Coreia do Sul',
    'Spain': 'Espanha',
    'Switzerland': 'Suíça',
    'Tunisia': 'Tunísia',
    'Uruguay': 'Uruguai',
    'USA': 'Estados Unidos',
    'Wales': 'País de Gales',
    'Korea Republic': 'Coreia do Sul',
    'South Africa': 'África do Sul',
    'Scotland': 'Escócia',
    'Haiti': 'Haiti',
    'Paraguay': 'Paraguai',
    'Curacao': 'Curaçao',
    'Curaçao': 'Curaçao',
    "Ivory Coast": 'Costa do Marfim',
    "Côte d'Ivoire": 'Costa do Marfim',
    "Cote d'Ivoire": 'Costa do Marfim',
    'Colombia': 'Colômbia',
    'Chile': 'Chile',
    'Peru': 'Peru',
    'Venezuela': 'Venezuela',
    'Bolivia': 'Bolívia',
    'Panama': 'Panamá',
    'Honduras': 'Honduras',
    'Jamaica': 'Jamaica',
    'Trinidad and Tobago': 'Trinidad e Tobago',
    'El Salvador': 'El Salvador',
    'Guatemala': 'Guatemala',
    'Algeria': 'Argélia',
    'Nigeria': 'Nigéria',
    'Egypt': 'Egito',
    'Burkina Faso': 'Burkina Faso',
    'New Zealand': 'Nova Zelândia',
    'Cabo Verde': 'Cabo Verde',
    'Norway': 'Noruega',
    'Austria': 'Áustria',
    'Jordan': 'Jordânia',
    'Uzbekistan': 'Uzbequistão',
    'Democratic Republic of the Congo': 'RD Congo',
    'DR Congo': 'RD Congo',
    'Turkey': 'Turquia',
    'Iraq': 'Iraque',
    'Bosnia and Herzegovina': 'Bósnia',
    'Sweden': 'Suécia',
    'Czech Republic': 'República Checa',
}

translations_reduced = {
    'Argentina': 'Argentina',
    'Australia': 'Austrália',
    'Belgium': 'Bélgica',
    'Brazil': 'Brasil',
    'Cameroon': 'Camarões',
    'Canada': 'Canadá',
    'Costa Rica': 'Costa Rica',
    'Croatia': 'Croácia',
    'Denmark': 'Dinamarca',
    'Ecuador': 'Equador',
    'England': 'Inglaterra',
    'France': 'França',
    'Germany': 'Alemanha',
    'Ghana': 'Gana',
    'Iran': 'Irã',
    'Japan': 'Japão',
    'Mexico': 'México',
    'Morocco': 'Marrocos',
    'Netherlands': 'Holanda',
    'Poland': 'Polônia',
    'Portugal': 'Portugal',
    'Qatar': 'Catar',
    'Saudi Arabia': 'Arábia S',
    'Senegal': 'Senegal',
    'Serbia': 'Sérvia',
    'South Korea': 'Coréia',
    'Spain': 'Espanha',
    'Switzerland': 'Suíça',
    'Tunisia': 'Tunísia',
    'Uruguay': 'Uruguai',
    'USA': 'EUA',
    'Wales': 'País de Gales',
    'Korea Republic': 'Coréia',
    'South Africa': 'África S',
    'Scotland': 'Escócia',
    'Haiti': 'Haiti',
    'Paraguay': 'Paraguai',
    'Curacao': 'Curaçao',
    'Curaçao': 'Curaçao',
    "Ivory Coast": 'Costa M',
    "Côte d'Ivoire": 'Costa M',
    "Cote d'Ivoire": 'Costa M',
    'Colombia': 'Colômbia',
    'Chile': 'Chile',
    'Peru': 'Peru',
    'Venezuela': 'Venezuela',
    'Bolivia': 'Bolívia',
    'Panama': 'Panamá',
    'Honduras': 'Honduras',
    'Jamaica': 'Jamaica',
    'Trinidad and Tobago': 'Trinidad e Tobago',
    'El Salvador': 'El Salvador',
    'Guatemala': 'Guatemala',
    'Algeria': 'Argélia',
    'Nigeria': 'Nigéria',
    'Egypt': 'Egito',
    'Burkina Faso': 'Burkina Faso',
    'New Zealand': 'Nova Z',
    'Cabo Verde': 'Cabo V',
    'Norway': 'Noruega',
    'Austria': 'Áustria',
    'Jordan': 'Jordânia',
    'Uzbekistan': 'Uzbequi',
    'Democratic Republic of the Congo': 'Congo',
    'DR Congo': 'Congo',
    'Turkey': 'Turquia',
    'Iraq': 'Iraque',
    'Bosnia and Herzegovina': 'Bósnia',
    'Sweden': 'Suécia',
    'Czech Republic': 'R Checa',
}


PLAYER_ALIASES = {
    # Mbappé
    "kylian mbappe": "Mbappé",
    "kylian mbappé": "Mbappé",
    "mbappe": "Mbappé",
    "mbappé": "Mbappé",
    "Mbape": "Mbappé",
    "mbape": "Mbappé",

    # Vinicius
    "vinicius junior": "Vini Jr.",
    "vinícius junior": "Vini Jr.",
    "vinicius jr": "Vini Jr.",
    "vinícius jr": "Vini Jr.",
    "vini jr": "Vini Jr.",
    "vini jr.": "Vini Jr.",

    # Igor Thiago
    "igor thiago pirulito": "Igor Thiago",
    "igor thiago": "Igor Thiago",

    # Lamine Yamal
    "lamina yamal": "Lamine Yamal",
    "yamal": "Lamine Yamal",

    # Harry Kane
    "kane": "Harry Kane",
    "harry kane": "Harry Kane",

    # Neymar
    "baleno": "Neymar",

    # Messi
    "lionel messi": "Messi",

    # haaland
    "erling haaland": "Haaland",

    # haaland
    "ousmane dembele": "Dembélé",

    # Oyarzabal
    "oyarzabal": "Oyarzabal",
    "mikel oyarzabal": "Oyarzabal",

    # Dani Olmo
    "dani olmo": "Dani Olmo",
    "olmo": "Dani Olmo",

    # Jude Bellingham
    "bellingham": "Jude Bellingham",
    "jude bellingham": "Jude Bellingham",

    # Oline
    "oline": "Oline",

}

CAMPEAO = ""

ARTILHEIRO = ""

MELHOR_JOGADOR = ""

ZEBRA = "Cabo Verde"

FAVORITO = "Germany"

ANFITRIAO = "Mexico"

# Country colors for UI theming (primary team color)
country_colors = {
    'Argentina': {'bg': 'bg-sky-500', 'hover': 'hover:bg-sky-600', 'text': 'text-sky-700', 'light': 'bg-sky-50', 'ring': 'ring-sky-400'},
    'Brazil': {'bg': 'bg-yellow-400', 'hover': 'hover:bg-yellow-500', 'text': 'text-yellow-700', 'light': 'bg-yellow-50', 'ring': 'ring-yellow-400'},
    'France': {'bg': 'bg-blue-600', 'hover': 'hover:bg-blue-700', 'text': 'text-blue-700', 'light': 'bg-blue-50', 'ring': 'ring-blue-400'},
    'Spain': {'bg': 'bg-red-600', 'hover': 'hover:bg-red-700', 'text': 'text-red-700', 'light': 'bg-red-50', 'ring': 'ring-red-400'},
    'England': {'bg': 'bg-red-600', 'hover': 'hover:bg-red-700', 'text': 'text-red-700', 'light': 'bg-red-50', 'ring': 'ring-red-400'},
    'Germany': {'bg': 'bg-slate-800', 'hover': 'hover:bg-slate-900', 'text': 'text-slate-700', 'light': 'bg-slate-50', 'ring': 'ring-slate-400'},
    'Italy': {'bg': 'bg-blue-600', 'hover': 'hover:bg-blue-700', 'text': 'text-blue-700', 'light': 'bg-blue-50', 'ring': 'ring-blue-400'},
    'Portugal': {'bg': 'bg-red-600', 'hover': 'hover:bg-red-700', 'text': 'text-red-700', 'light': 'bg-red-50', 'ring': 'ring-red-400'},
    'Netherlands': {'bg': 'bg-orange-500', 'hover': 'hover:bg-orange-600', 'text': 'text-orange-700', 'light': 'bg-orange-50', 'ring': 'ring-orange-400'},
    'Belgium': {'bg': 'bg-red-600', 'hover': 'hover:bg-red-700', 'text': 'text-red-700', 'light': 'bg-red-50', 'ring': 'ring-red-400'},
    'Uruguay': {'bg': 'bg-sky-500', 'hover': 'hover:bg-sky-600', 'text': 'text-sky-700', 'light': 'bg-sky-50', 'ring': 'ring-sky-400'},
    'Croatia': {'bg': 'bg-red-600', 'hover': 'hover:bg-red-700', 'text': 'text-red-700', 'light': 'bg-red-50', 'ring': 'ring-red-400'},
    'Mexico': {'bg': 'bg-green-600', 'hover': 'hover:bg-green-700', 'text': 'text-green-700', 'light': 'bg-green-50', 'ring': 'ring-green-400'},
    'USA': {'bg': 'bg-blue-700', 'hover': 'hover:bg-blue-800', 'text': 'text-blue-700', 'light': 'bg-blue-50', 'ring': 'ring-blue-400'},
    'Colombia': {'bg': 'bg-yellow-400', 'hover': 'hover:bg-yellow-500', 'text': 'text-yellow-700', 'light': 'bg-yellow-50', 'ring': 'ring-yellow-400'},
    'Japan': {'bg': 'bg-blue-600', 'hover': 'hover:bg-blue-700', 'text': 'text-blue-700', 'light': 'bg-blue-50', 'ring': 'ring-blue-400'},
    'Morocco': {'bg': 'bg-red-600', 'hover': 'hover:bg-red-700', 'text': 'text-red-700', 'light': 'bg-red-50', 'ring': 'ring-red-400'},
    'Senegal': {'bg': 'bg-green-600', 'hover': 'hover:bg-green-700', 'text': 'text-green-700', 'light': 'bg-green-50', 'ring': 'ring-green-400'},
    'Switzerland': {'bg': 'bg-red-600', 'hover': 'hover:bg-red-700', 'text': 'text-red-700', 'light': 'bg-red-50', 'ring': 'ring-red-400'},
    'Denmark': {'bg': 'bg-red-600', 'hover': 'hover:bg-red-700', 'text': 'text-red-700', 'light': 'bg-red-50', 'ring': 'ring-red-400'},
    'South Korea': {'bg': 'bg-red-600', 'hover': 'hover:bg-red-700', 'text': 'text-red-700', 'light': 'bg-red-50', 'ring': 'ring-red-400'},
    'Korea Republic': {'bg': 'bg-red-600', 'hover': 'hover:bg-red-700', 'text': 'text-red-700', 'light': 'bg-red-50', 'ring': 'ring-red-400'},
    'Ecuador': {'bg': 'bg-yellow-400', 'hover': 'hover:bg-yellow-500', 'text': 'text-yellow-700', 'light': 'bg-yellow-50', 'ring': 'ring-yellow-400'},
    'Poland': {'bg': 'bg-red-600', 'hover': 'hover:bg-red-700', 'text': 'text-red-700', 'light': 'bg-red-50', 'ring': 'ring-red-400'},
    'Australia': {'bg': 'bg-yellow-400', 'hover': 'hover:bg-yellow-500', 'text': 'text-yellow-700', 'light': 'bg-yellow-50', 'ring': 'ring-yellow-400'},
    'Canada': {'bg': 'bg-red-600', 'hover': 'hover:bg-red-700', 'text': 'text-red-700', 'light': 'bg-red-50', 'ring': 'ring-red-400'},
    'Ghana': {'bg': 'bg-red-600', 'hover': 'hover:bg-red-700', 'text': 'text-red-700', 'light': 'bg-red-50', 'ring': 'ring-red-400'},
    'Cameroon': {'bg': 'bg-green-600', 'hover': 'hover:bg-green-700', 'text': 'text-green-700', 'light': 'bg-green-50', 'ring': 'ring-green-400'},
    'Nigeria': {'bg': 'bg-green-600', 'hover': 'hover:bg-green-700', 'text': 'text-green-700', 'light': 'bg-green-50', 'ring': 'ring-green-400'},
    'Tunisia': {'bg': 'bg-red-600', 'hover': 'hover:bg-red-700', 'text': 'text-red-700', 'light': 'bg-red-50', 'ring': 'ring-red-400'},
    'Algeria': {'bg': 'bg-green-600', 'hover': 'hover:bg-green-700', 'text': 'text-green-700', 'light': 'bg-green-50', 'ring': 'ring-green-400'},
    'Egypt': {'bg': 'bg-red-600', 'hover': 'hover:bg-red-700', 'text': 'text-red-700', 'light': 'bg-red-50', 'ring': 'ring-red-400'},
    'Iran': {'bg': 'bg-green-600', 'hover': 'hover:bg-green-700', 'text': 'text-green-700', 'light': 'bg-green-50', 'ring': 'ring-green-400'},
    'IR Iran': {'bg': 'bg-green-600', 'hover': 'hover:bg-green-700', 'text': 'text-green-700', 'light': 'bg-green-50', 'ring': 'ring-green-400'},
    'Saudi Arabia': {'bg': 'bg-green-600', 'hover': 'hover:bg-green-700', 'text': 'text-green-700', 'light': 'bg-green-50', 'ring': 'ring-green-400'},
    'Costa Rica': {'bg': 'bg-red-600', 'hover': 'hover:bg-red-700', 'text': 'text-red-700', 'light': 'bg-red-50', 'ring': 'ring-red-400'},
    'Serbia': {'bg': 'bg-red-600', 'hover': 'hover:bg-red-700', 'text': 'text-red-700', 'light': 'bg-red-50', 'ring': 'ring-red-400'},
    'Wales': {'bg': 'bg-red-600', 'hover': 'hover:bg-red-700', 'text': 'text-red-700', 'light': 'bg-red-50', 'ring': 'ring-red-400'},
    'Turkey': {'bg': 'bg-red-600', 'hover': 'hover:bg-red-700', 'text': 'text-red-700', 'light': 'bg-red-50', 'ring': 'ring-red-400'},
    'Türkiye': {'bg': 'bg-red-600', 'hover': 'hover:bg-red-700', 'text': 'text-red-700', 'light': 'bg-red-50', 'ring': 'ring-red-400'},
    'Austria': {'bg': 'bg-red-600', 'hover': 'hover:bg-red-700', 'text': 'text-red-700', 'light': 'bg-red-50', 'ring': 'ring-red-400'},
    'Sweden': {'bg': 'bg-blue-500', 'hover': 'hover:bg-blue-600', 'text': 'text-blue-700', 'light': 'bg-blue-50', 'ring': 'ring-blue-400'},
    'Norway': {'bg': 'bg-red-600', 'hover': 'hover:bg-red-700', 'text': 'text-red-700', 'light': 'bg-red-50', 'ring': 'ring-red-400'},
    'Scotland': {'bg': 'bg-blue-600', 'hover': 'hover:bg-blue-700', 'text': 'text-blue-700', 'light': 'bg-blue-50', 'ring': 'ring-blue-400'},
    'Ukraine': {'bg': 'bg-blue-500', 'hover': 'hover:bg-blue-600', 'text': 'text-blue-700', 'light': 'bg-blue-50', 'ring': 'ring-blue-400'},
}

# Default color scheme for countries not in the list
default_country_color = {'bg': 'bg-blue-500', 'hover': 'hover:bg-blue-600', 'text': 'text-blue-700', 'light': 'bg-blue-50', 'ring': 'ring-blue-400'}

# FIFA World Rankings (Official, January 2025)
# Lower number = better ranking (1 is best)
# Used as final tiebreaker for group standings
fifa_ranking = {
    'Argentina': 1,
    'Spain': 2,
    'France': 3,
    'England': 4,
    'Portugal': 5,
    'Brazil': 6,
    'Morocco': 7,
    'Netherlands': 8,
    'Belgium': 9,
    'Germany': 10,
    'Croatia': 11,
    'Italy': 12,
    'Colombia': 13,
    'Mexico': 14,
    'Senegal': 15,
    'Uruguay': 16,
    'USA': 17,
    'Japan': 18,
    'Switzerland': 19,
    'IR Iran': 20,
    'Iran': 20,
    'Denmark': 21,
    'Türkiye': 22,
    'Turkey': 22,
    'Ecuador': 23,
    'Austria': 24,
    'Korea Republic': 25,
    'South Korea': 25,
    'Nigeria': 26,
    'Australia': 27,
    'Algeria': 28,
    'Egypt': 29,
    'Canada': 30,
    'Norway': 31,
    'Ukraine': 32,
    "Côte d'Ivoire": 33,
    "Cote d'Ivoire": 33,
    'Ivory Coast': 33,
    'Panama': 34,
    'Russia': 35,
    'Poland': 36,
    'Wales': 37,
    'Sweden': 38,
    'Hungary': 39,
    'Czechia': 40,
    'Czech Republic': 40,
    'Paraguay': 41,
    'Scotland': 42,
    'Serbia': 43,
    'Cameroon': 44,
    'Tunisia': 45,
    'Congo DR': 46,
    'DR Congo': 46,
    'Democratic Republic of the Congo': 46,
    'Slovakia': 47,
    'Greece': 48,
    'Venezuela': 49,
    'Uzbekistan': 50,
    'Chile': 51,
    'Peru': 52,
    'Costa Rica': 53,
    'Romania': 54,
    'Mali': 55,
    'Qatar': 56,
    'Iraq': 57,
    'Republic of Ireland': 58,
    'Slovenia': 59,
    'South Africa': 60,
    'Saudi Arabia': 61,
    'Burkina Faso': 62,
    'Jordan': 63,
    'Bosnia and Herzegovina': 64,
    'Honduras': 65,
    'Albania': 66,
    'Cabo Verde': 67,
    'United Arab Emirates': 68,
    'North Macedonia': 69,
    'Northern Ireland': 70,
    'Jamaica': 71,
    'Georgia': 72,
    'Ghana': 73,
    'Iceland': 74,
    'Finland': 75,
    'Israel': 76,
    'Bolivia': 77,
    'Kosovo': 78,
    'Oman': 79,
    'Montenegro': 80,
    'Guinea': 81,
    'Curaçao': 82,
    'Curacao': 82,
    'Haiti': 83,
    'Syria': 84,
    'New Zealand': 85,
    'El Salvador': 100,
    'Guatemala': 97,
    'Trinidad and Tobago': 102,
}
